### ISSUE TITLE
The "gv.vim" is not working.

### ISSUE THREAD

**Issue by eos33** [archerindigo/vimrc#2]
Hi , 
First, Thank you for your sharing and it's really useful to new users of Vi.
Could you please help to check the "gv.vim" is not working?
Thanks.

**Comment by archerindigo** [comment]
@eos33 Sorry for very late reply as I accidentally turned off the notification.

I just released v1.0.0 which included a fix to your problem. You can have a try.

Alternatively, you can run `:PlugClean` and then `:PlugUpdate` in vim to reinstall the plugins.
